export interface TurkishWord {
  ky: string;
  tr: string;
  reading: string;
  example: string;
}

export interface WordCategory {
  id: string;
  title: string;
  icon: string;
  words: TurkishWord[];
}

export const alphabet = [
  { letter: 'A', sound: 'а', example: 'anne - апа' },
  { letter: 'B', sound: 'б', example: 'baba - ата' },
  { letter: 'C', sound: 'ж', example: 'cam - айнек' },
  { letter: 'Ç', sound: 'ч', example: 'çay - чай' },
  { letter: 'D', sound: 'д', example: 'ders - сабак' },
  { letter: 'E', sound: 'э', example: 'ev - үй' },
  { letter: 'F', sound: 'ф', example: 'fırın - нан бышыруучу жай' },
  { letter: 'G', sound: 'г', example: 'gün - күн' },
  { letter: 'Ğ', sound: 'жумшак созулат', example: 'dağ - тоо' },
  { letter: 'H', sound: 'х', example: 'hava - аба' },
  { letter: 'I', sound: 'ы', example: 'ışık - жарык' },
  { letter: 'İ', sound: 'и', example: 'isim - ат' },
  { letter: 'J', sound: 'ж', example: 'jandarma - жандарм' },
  { letter: 'K', sound: 'к', example: 'kitap - китеп' },
  { letter: 'L', sound: 'л', example: 'limon - лимон' },
  { letter: 'M', sound: 'м', example: 'masa - стол' },
  { letter: 'N', sound: 'н', example: 'nasıl - кандай' },
  { letter: 'O', sound: 'о', example: 'okul - мектеп' },
  { letter: 'Ö', sound: 'ө', example: 'öğrenci - окуучу' },
  { letter: 'P', sound: 'п', example: 'para - акча' },
  { letter: 'R', sound: 'р', example: 'renk - түс' },
  { letter: 'S', sound: 'с', example: 'saat - саат' },
  { letter: 'Ş', sound: 'ш', example: 'şehir - шаар' },
  { letter: 'T', sound: 'т', example: 'tahta - такта' },
  { letter: 'U', sound: 'у', example: 'uzun - узун' },
  { letter: 'Ü', sound: 'ү', example: 'üzüm - жүзүм' },
  { letter: 'V', sound: 'в', example: 'var - бар' },
  { letter: 'Y', sound: 'й', example: 'yol - жол' },
  { letter: 'Z', sound: 'з', example: 'zaman - убакыт' },
];

export const grammarTopics = [
  {
    title: 'Мен, сен, ал',
    rule: 'Түркчөдө адам ат атоочтору: ben - мен, sen - сен, o - ал, biz - биз, siz - сиз, onlar - алар.',
    example: 'Ben öğrenciyim. - Мен окуучумун.',
  },
  {
    title: 'Көптүк мүчө -lar / -ler',
    rule: 'Сөздүн үндүүсүнө жараша -lar же -ler кошулат.',
    example: 'kitaplar - китептер, öğrenciler - окуучулар.',
  },
  {
    title: 'Суроо мүчөсү mi / mı / mu / mü',
    rule: 'Суроо мүчөсү сөздөгү үндүүгө жараша өзгөрөт.',
    example: 'Bu kitap mı? - Бул китеппи?',
  },
  {
    title: 'Бар / жок',
    rule: 'var - бар, yok - жок.',
    example: 'Kalem var. - Калем бар. Para yok. - Акча жок.',
  },
  {
    title: 'Азыркы чак -yor',
    rule: 'Кыймыл азыр болуп жатканын билдирет.',
    example: 'Ben okuyorum. - Мен окуп жатам.',
  },
  {
    title: 'Жайгашуу: -da / -de',
    rule: 'Бир нерсе кайда экенин көрсөтөт.',
    example: 'Okulda. - Мектепте. Evde. - Үйдө.',
  },
  {
    title: 'Таандык мүчө',
    rule: 'Бир нерсе кимдики экенин көрсөтөт: benim - менин, senin - сенин, onun - анын.',
    example: 'Benim kitabım. - Менин китебим.',
  },
  {
    title: 'Өткөн чак -di',
    rule: 'Болуп өткөн ишти билдирет. Үндүүгө жараша -dı, -di, -du, -dü болуп өзгөрөт.',
    example: 'Okula gittim. - Мен мектепке бардым.',
  },
  {
    title: 'Каалоо: istiyorum',
    rule: 'Бир нерсени каалаганда “istiyorum” колдонулат.',
    example: 'Su istiyorum. - Суу каалайм.',
  },
  {
    title: 'Керек: lazım / gerek',
    rule: 'Бир нерсе керек экенин билдирет.',
    example: 'Bana kalem lazım. - Мага калем керек.',
  },
];

export const dialogs = [
  {
    title: 'Таанышуу',
    lines: [
      ['Merhaba!', 'Салам!'],
      ['Adın ne?', 'Атың ким?'],
      ['Benim adım Aybek.', 'Менин атым Айбек.'],
      ['Memnun oldum.', 'Таанышканыма кубанычтамын.'],
    ],
  },
  {
    title: 'Мектепте',
    lines: [
      ['Ders ne zaman başlıyor?', 'Сабак качан башталат?'],
      ['Ders saat sekizde başlıyor.', 'Сабак саат сегизде башталат.'],
      ['Kitabın var mı?', 'Китебиң барбы?'],
      ['Evet, kitabım var.', 'Ооба, китебим бар.'],
    ],
  },
  {
    title: 'Дүкөндө',
    lines: [
      ['Bu ne kadar?', 'Бул канча турат?'],
      ['Bu elli lira.', 'Бул элүү лира.'],
      ['Bir ekmek alabilir miyim?', 'Бир нан алсам болобу?'],
      ['Tabii, buyurun.', 'Албетте, алыңыз.'],
    ],
  },
  {
    title: 'Жол суроо',
    lines: [
      ['Affedersiniz, okul nerede?', 'Кечиресиз, мектеп кайда?'],
      ['Düz gidin, sonra sağa dönün.', 'Түз барыңыз, анан оңго бурулуңуз.'],
      ['Uzak mı?', 'Алыспы?'],
      ['Hayır, çok yakın.', 'Жок, абдан жакын.'],
    ],
  },
  {
    title: 'Дарыгерде',
    lines: [
      ['Kendimi iyi hissetmiyorum.', 'Өзүмдү жакшы сезбей жатам.'],
      ['Neren ağrıyor?', 'Кайсы жериң ооруп жатат?'],
      ['Başım ağrıyor.', 'Башым ооруп жатат.'],
      ['Bol su içmelisin.', 'Көп суу ичишиң керек.'],
    ],
  },
  {
    title: 'Телефон аркылуу',
    lines: [
      ['Merhaba, beni duyuyor musun?', 'Салам, мени угуп жатасыңбы?'],
      ['Evet, duyuyorum.', 'Ооба, угуп жатам.'],
      ['Sonra arayabilir miyim?', 'Кийин чалсам болобу?'],
      ['Tabii, sorun değil.', 'Албетте, маселе жок.'],
    ],
  },
];

const w = (ky: string, tr: string, reading: string, example: string): TurkishWord => ({ ky, tr, reading, example });

export const wordCategories: WordCategory[] = [
  {
    id: 'greetings',
    title: 'Саламдашуу',
    icon: '👋',
    words: [
      w('салам', 'merhaba', 'мерхаба', 'Merhaba, nasılsın?'),
      w('саламатсызбы', 'selamünaleyküm', 'селамүналейкүм', 'Selamünaleyküm hocam.'),
      w('кандайсың', 'nasılsın', 'насылсын', 'Sen nasılsın?'),
      w('жакшы', 'iyi', 'ийи', 'Ben iyiyim.'),
      w('рахмат', 'teşekkür ederim', 'тешеккүр эдерим', 'Teşekkür ederim.'),
      w('суранам', 'lütfen', 'лүтфен', 'Lütfen yardım et.'),
      w('кечиресиз', 'affedersiniz', 'аффедерсиниз', 'Affedersiniz, okul nerede?'),
      w('кош бол', 'hoşça kal', 'хошча кал', 'Hoşça kal arkadaşım.'),
      w('көрүшкөнчө', 'görüşürüz', 'гөрүшүрүз', 'Yarın görüşürüz.'),
      w('макул', 'tamam', 'тамам', 'Tamam, geliyorum.'),
    ],
  },
  {
    id: 'school',
    title: 'Мектеп',
    icon: '🏫',
    words: [
      w('мектеп', 'okul', 'окул', 'Okul çok güzel.'),
      w('окуучу', 'öğrenci', 'өөренжи', 'Ben öğrenciyim.'),
      w('мугалим', 'öğretmen', 'өөретмен', 'Öğretmen sınıfta.'),
      w('сабак', 'ders', 'дерс', 'Ders başladı.'),
      w('класс', 'sınıf', 'сыныф', 'Sınıf temiz.'),
      w('китеп', 'kitap', 'китап', 'Kitap masada.'),
      w('дептер', 'defter', 'дефтер', 'Defter bende.'),
      w('калем', 'kalem', 'калем', 'Kalem var mı?'),
      w('такта', 'tahta', 'тахта', 'Tahta beyaz.'),
      w('үй тапшырма', 'ödev', 'өдев', 'Ödevimi yaptım.'),
      w('экзамен', 'sınav', 'сынав', 'Sınav zor değil.'),
      w('баа', 'not', 'нот', 'Notum iyi.'),
    ],
  },
  {
    id: 'family',
    title: 'Үй-бүлө',
    icon: '👨‍👩‍👧‍👦',
    words: [
      w('үй-бүлө', 'aile', 'айле', 'Ailem büyük.'),
      w('ата', 'baba', 'баба', 'Babam çalışıyor.'),
      w('апа', 'anne', 'анне', 'Annem evde.'),
      w('ага', 'ağabey', 'аабей', 'Ağabeyim öğrenci.'),
      w('эже', 'abla', 'абла', 'Ablam kitap okuyor.'),
      w('ини', 'erkek kardeş', 'эркек кардеш', 'Erkek kardeşim küçük.'),
      w('карындаш/сиңди', 'kız kardeş', 'кыз кардеш', 'Kız kardeşim okulda.'),
      w('чоң ата', 'dede', 'деде', 'Dedem köyde.'),
      w('чоң апа', 'nine', 'нине', 'Ninem yemek yapıyor.'),
      w('дос', 'arkadaş', 'аркадаш', 'Arkadaşım geldi.'),
    ],
  },
  {
    id: 'numbers',
    title: 'Сандар',
    icon: '🔢',
    words: [
      w('бир', 'bir', 'бир', 'Bir kitap.'),
      w('эки', 'iki', 'ики', 'İki kalem.'),
      w('үч', 'üç', 'үч', 'Üç öğrenci.'),
      w('төрт', 'dört', 'дөрт', 'Dört masa.'),
      w('беш', 'beş', 'беш', 'Beş defter.'),
      w('алты', 'altı', 'алты', 'Altı gün.'),
      w('жети', 'yedi', 'йеди', 'Yedi kişi.'),
      w('сегиз', 'sekiz', 'секиз', 'Sekiz saat.'),
      w('тогуз', 'dokuz', 'докуз', 'Dokuz soru.'),
      w('он', 'on', 'он', 'On cevap.'),
      w('жыйырма', 'yirmi', 'йирми', 'Yirmi lira.'),
      w('жүз', 'yüz', 'йүз', 'Yüz puan.'),
    ],
  },
  {
    id: 'time',
    title: 'Убакыт',
    icon: '⏰',
    words: [
      w('бүгүн', 'bugün', 'бүгүн', 'Bugün ders var.'),
      w('эртең', 'yarın', 'ярын', 'Yarın geliyorum.'),
      w('кечээ', 'dün', 'дүн', 'Dün okuldaydım.'),
      w('азыр', 'şimdi', 'шимди', 'Şimdi okuyorum.'),
      w('эртең менен', 'sabah', 'сабах', 'Sabah erken kalktım.'),
      w('түштө', 'öğlen', 'өлен', 'Öğlen yemek yedim.'),
      w('кечинде', 'akşam', 'акшам', 'Akşam evdeyim.'),
      w('түн', 'gece', 'гедже', 'Gece uyuyorum.'),
      w('саат', 'saat', 'саат', 'Saat kaç?'),
      w('жума', 'hafta', 'хафта', 'Bu hafta sınav var.'),
    ],
  },
  {
    id: 'food',
    title: 'Тамак-аш',
    icon: '🍽️',
    words: [
      w('нан', 'ekmek', 'экмек', 'Ekmek taze.'),
      w('суу', 'su', 'су', 'Su içiyorum.'),
      w('чай', 'çay', 'чай', 'Çay sıcak.'),
      w('сүт', 'süt', 'сүт', 'Süt beyaz.'),
      w('тамак', 'yemek', 'йемек', 'Yemek hazır.'),
      w('алма', 'elma', 'элма', 'Elma yiyorum.'),
      w('жүзүм', 'üzüm', 'үзүм', 'Üzüm tatlı.'),
      w('шорпо', 'çorba', 'чорба', 'Çorba içiyorum.'),
      w('эт', 'et', 'эт', 'Et pahalı.'),
      w('туз', 'tuz', 'туз', 'Tuz nerede?'),
      w('кант', 'şeker', 'шекер', 'Şeker az.'),
      w('жумуртка', 'yumurta', 'юмурта', 'Yumurta aldım.'),
    ],
  },
  {
    id: 'verbs',
    title: 'Этиштер',
    icon: '🏃',
    words: [
      w('баруу', 'gitmek', 'гитмек', 'Okula gidiyorum.'),
      w('келүү', 'gelmek', 'гелмек', 'Eve geliyorum.'),
      w('окуу', 'okumak', 'окумак', 'Kitap okuyorum.'),
      w('жазуу', 'yazmak', 'язмак', 'Deftere yazıyorum.'),
      w('сүйлөө', 'konuşmak', 'конушмак', 'Türkçe konuşuyorum.'),
      w('угуу', 'dinlemek', 'динлемек', 'Müzik dinliyorum.'),
      w('көрүү', 'görmek', 'гөрмек', 'Seni görüyorum.'),
      w('билүү', 'bilmek', 'билмек', 'Bunu biliyorum.'),
      w('үйрөнүү', 'öğrenmek', 'өөренмек', 'Türkçe öğreniyorum.'),
      w('иштөө', 'çalışmak', 'чалышмак', 'Ben çalışıyorum.'),
      w('жашоо', 'yaşamak', 'яшамак', "Bişkek'te yaşıyorum."),
      w('суроо', 'sormak', 'сормак', 'Soru soruyorum.'),
    ],
  },
  {
    id: 'places',
    title: 'Жерлер',
    icon: '📍',
    words: [
      w('үй', 'ev', 'эв', 'Ev büyük.'),
      w('айыл', 'köy', 'көй', 'Köy güzel.'),
      w('шаар', 'şehir', 'шехир', 'Şehir kalabalık.'),
      w('көчө', 'sokak', 'сокак', 'Sokak temiz.'),
      w('базар', 'pazar', 'пазар', 'Pazara gidiyorum.'),
      w('дүкөн', 'mağaza', 'мааза', 'Mağaza açık.'),
      w('оорукана', 'hastane', 'хастане', 'Hastane yakın.'),
      w('китепкана', 'kütüphane', 'күтүпхане', 'Kütüphanede okuyorum.'),
      w('ашкана', 'yemekhane', 'йемекхане', 'Yemekhane okulda.'),
      w('спорт зал', 'spor salonu', 'спор салону', 'Spor salonu büyük.'),
    ],
  },
  {
    id: 'adjectives',
    title: 'Сын атоочтор',
    icon: '✨',
    words: [
      w('жакшы', 'iyi', 'ийи', 'İyi bir gün.'),
      w('жаман', 'kötü', 'көтү', 'Kötü hava.'),
      w('чоң', 'büyük', 'бүйүк', 'Büyük okul.'),
      w('кичине', 'küçük', 'күчүк', 'Küçük ev.'),
      w('жаңы', 'yeni', 'йени', 'Yeni kitap.'),
      w('эски', 'eski', 'эски', 'Eski defter.'),
      w('сулуу', 'güzel', 'гүзел', 'Güzel şehir.'),
      w('тез', 'hızlı', 'хызлы', 'Hızlı öğrenci.'),
      w('жай', 'yavaş', 'яваш', 'Yavaş konuş.'),
      w('кыйын', 'zor', 'зор', 'Bu soru zor.'),
      w('оңой', 'kolay', 'колай', 'Türkçe kolay.'),
      w('ысык', 'sıcak', 'сыжак', 'Çay sıcak.'),
    ],
  },
  {
    id: 'daily',
    title: 'Күнүмдүк сөздөр',
    icon: '🧭',
    words: [
      w('ооба', 'evet', 'эвет', 'Evet, biliyorum.'),
      w('жок', 'hayır', 'хайыр', 'Hayır, bilmiyorum.'),
      w('бар', 'var', 'вар', 'Kitap var.'),
      w('жок', 'yok', 'йок', 'Para yok.'),
      w('бул', 'bu', 'бу', 'Bu nedir?'),
      w('тигил', 'şu', 'шу', 'Şu okul.'),
      w('ал', 'o', 'о', 'O benim arkadaşım.'),
      w('ким', 'kim', 'ким', 'Bu kim?'),
      w('эмне', 'ne', 'не', 'Bu ne?'),
      w('кайда', 'nerede', 'нереде', 'Okul nerede?'),
      w('канча', 'kaç', 'кач', 'Saat kaç?'),
      w('эмне үчүн', 'neden', 'неден', 'Neden gelmedin?'),
    ],
  },
  {
    id: 'phrases',
    title: 'Сүйлөмдөр',
    icon: '💬',
    words: [
      w('Мен түркчө үйрөнүп жатам', 'Türkçe öğreniyorum', 'түркче өйрениёрум', 'Türkçe öğreniyorum.'),
      w('Мен мектепке барам', 'Okula gidiyorum', 'окула гидийорум', 'Okula gidiyorum.'),
      w('Сен кайда жашайсың?', 'Nerede yaşıyorsun?', 'нереде яшыйорсун', 'Nerede yaşıyorsun?'),
      w('Мен Кыргызстанда жашайм', 'Kırgızistan’da yaşıyorum', 'кыргызистанда яшыйорум', 'Kırgızistan’da yaşıyorum.'),
      w('Бул канча турат?', 'Bu ne kadar?', 'бу не кадар', 'Bu ne kadar?'),
      w('Мен түшүндүм', 'Anladım', 'анладым', 'Evet, anladım.'),
      w('Мен түшүнгөн жокмун', 'Anlamadım', 'анламадым', 'Anlamadım, tekrar eder misin?'),
      w('Кайра айтасызбы?', 'Tekrar eder misiniz?', 'текрар эдер мисиниз', 'Tekrar eder misiniz?'),
      w('Жардам бере аласызбы?', 'Yardım eder misiniz?', 'ярдым эдер мисиниз', 'Yardım eder misiniz?'),
      w('Менин атым Айбек', 'Benim adım Aybek', 'беним адым айбек', 'Benim adım Aybek.'),
    ],
  },
  {
    id: 'speaking',
    title: 'Сүйлөө фразалары',
    icon: '🗣️',
    words: [
      w('Мен түркчө аз сүйлөйм', 'Biraz Türkçe konuşuyorum', 'бираз түркче конушуйорум', 'Biraz Türkçe konuşuyorum.'),
      w('Жай сүйлөңүзчү', 'Yavaş konuşur musunuz?', 'яваш конушур мусунуз', 'Yavaş konuşur musunuz?'),
      w('Мага жардам керек', 'Yardıma ihtiyacım var', 'ярдыма ихтияжым вар', 'Yardıma ihtiyacım var.'),
      w('Мен сурайын дедим эле', 'Bir şey sormak istiyorum', 'бир шей сормак истийорум', 'Bir şey sormak istiyorum.'),
      w('Бул эмнени билдирет?', 'Bu ne demek?', 'бу не демек', 'Bu ne demek?'),
      w('Кантип айтылат?', 'Nasıl söylenir?', 'насыл сойленир', 'Bu Türkçe nasıl söylenir?'),
      w('Кайсынысы туура?', 'Hangisi doğru?', 'хангиси доору', 'Hangisi doğru?'),
      w('Мен макулмун', 'Katılıyorum', 'катылыйорум', 'Sana katılıyorum.'),
      w('Мен макул эмесмин', 'Katılmıyorum', 'катылмыйорум', 'Ben katılmıyorum.'),
      w('Эч нерсе эмес', 'Önemli değil', 'өнемли деил', 'Önemli değil, sorun yok.'),
      w('Кабатыр болбо', 'Merak etme', 'мерак этме', 'Merak etme, ben buradayım.'),
      w('Баары жакшы болот', 'Her şey iyi olacak', 'хер шей ийи олажак', 'Her şey iyi olacak.'),
    ],
  },
  {
    id: 'people',
    title: 'Адамдар жана кесип',
    icon: '👥',
    words: [
      w('адам', 'insan', 'инсан', 'İnsanlar konuşuyor.'),
      w('бала', 'çocuk', 'чожук', 'Çocuk parkta oynuyor.'),
      w('кыз', 'kız', 'кыз', 'Kız kitap okuyor.'),
      w('эркек', 'erkek', 'эркек', 'Erkek öğretmen.'),
      w('аял', 'kadın', 'кадын', 'Kadın doktor.'),
      w('мырза', 'bey', 'бей', 'Ali Bey burada.'),
      w('айым', 'hanım', 'ханым', 'Ayşe Hanım öğretmen.'),
      w('дарыгер', 'doktor', 'доктор', 'Doktor hastanede.'),
      w('инженер', 'mühendis', 'мүхендис', 'Mühendis çalışıyor.'),
      w('сатуучу', 'satıcı', 'сатыжы', 'Satıcı yardım etti.'),
      w('айдоочу', 'şoför', 'шофөр', 'Şoför bekliyor.'),
      w('программист', 'programcı', 'програмжы', 'Programcı bilgisayar kullanıyor.'),
    ],
  },
  {
    id: 'body-health',
    title: 'Ден соолук',
    icon: '🩺',
    words: [
      w('баш', 'baş', 'баш', 'Başım ağrıyor.'),
      w('көз', 'göz', 'гөз', 'Gözüm iyi görüyor.'),
      w('кулак', 'kulak', 'кулак', 'Kulağım ağrıyor.'),
      w('кол', 'el', 'эл', 'Elimi yıkadım.'),
      w('бут', 'ayak', 'аяк', 'Ayağım ağrıyor.'),
      w('жүрөк', 'kalp', 'калп', 'Kalbim hızlı atıyor.'),
      w('оору', 'ağrı', 'аары', 'Ağrım var.'),
      w('дары', 'ilaç', 'илач', 'İlaç aldım.'),
      w('оорукана', 'hastane', 'хастане', 'Hastaneye gidiyorum.'),
      w('температура', 'ateş', 'атеш', 'Ateşim var.'),
      w('жөтөл', 'öksürük', 'өксүрүк', 'Öksürüğüm var.'),
      w('ден соолук', 'sağlık', 'саалык', 'Sağlık önemlidir.'),
    ],
  },
  {
    id: 'weather',
    title: 'Аба ырайы',
    icon: '🌦️',
    words: [
      w('аба ырайы', 'hava durumu', 'хава дуруму', 'Hava durumu nasıl?'),
      w('күн ачык', 'güneşli', 'гүнешли', 'Bugün hava güneşli.'),
      w('жамгыр', 'yağmur', 'яамур', 'Yağmur yağıyor.'),
      w('кар', 'kar', 'кар', 'Kar yağıyor.'),
      w('шамал', 'rüzgar', 'рүзгар', 'Rüzgar güçlü.'),
      w('булуттуу', 'bulutlu', 'булутлу', 'Hava bulutlu.'),
      w('суук', 'soğuk', 'соок', 'Bugün hava soğuk.'),
      w('ысык', 'sıcak', 'сыжак', 'Hava çok sıcak.'),
      w('жылуу', 'ılık', 'ылык', 'Hava ılık.'),
      w('нымдуу', 'nemli', 'немли', 'Hava nemli.'),
      w('туман', 'sis', 'сис', 'Sabah sis vardı.'),
      w('чагылган', 'şimşek', 'шимшек', 'Şimşek çaktı.'),
    ],
  },
  {
    id: 'transport',
    title: 'Транспорт',
    icon: '🚌',
    words: [
      w('унаа', 'araba', 'араба', 'Araba hızlı gidiyor.'),
      w('автобус', 'otobüs', 'отобүс', 'Otobüs durağa geldi.'),
      w('такси', 'taksi', 'такси', 'Taksi çağırdım.'),
      w('поезд', 'tren', 'трен', 'Tren saat kaçta?'),
      w('учак', 'uçak', 'учак', 'Uçak kalkıyor.'),
      w('аялдама', 'durak', 'дурак', 'Durak nerede?'),
      w('билет', 'bilet', 'билет', 'Bilet aldım.'),
      w('жол', 'yol', 'йол', 'Yol uzun.'),
      w('солго бурул', 'sola dön', 'сола дөн', 'Sola dönün.'),
      w('оңго бурул', 'sağa dön', 'саа дөн', 'Sağa dönün.'),
      w('түз бар', 'düz git', 'дүз гит', 'Düz git.'),
      w('жакын', 'yakın', 'яАкын', 'Okul buraya yakın.'),
    ],
  },
  {
    id: 'shopping',
    title: 'Соода',
    icon: '🛒',
    words: [
      w('акча', 'para', 'пара', 'Param var.'),
      w('баа', 'fiyat', 'фият', 'Fiyat uygun.'),
      w('арзан', 'ucuz', 'ужуз', 'Bu ürün ucuz.'),
      w('кымбат', 'pahalı', 'пахалы', 'Bu telefon pahalı.'),
      w('сатып алуу', 'satın almak', 'сатын алмак', 'Kitap satın aldım.'),
      w('сатуу', 'satmak', 'сатмак', 'Satıcı ekmek satıyor.'),
      w('дүмүрчөк', 'fiş', 'фиш', 'Fiş alabilir miyim?'),
      w('карта', 'kart', 'карт', 'Kartla ödeyebilir miyim?'),
      w('нак акча', 'nakit', 'накит', 'Nakit ödeyeceğim.'),
      w('өлчөм', 'beden', 'беден', 'Bedeniniz nedir?'),
      w('түс', 'renk', 'ренк', 'Bu renk güzel.'),
      w('баштык', 'poşet', 'пошет', 'Poşet ister misiniz?'),
    ],
  },
  {
    id: 'clothes',
    title: 'Кийим',
    icon: '👕',
    words: [
      w('кийим', 'kıyafet', 'кыяфет', 'Kıyafet güzel.'),
      w('көйнөк', 'gömlek', 'гөмлек', 'Gömlek beyaz.'),
      w('шым', 'pantolon', 'пантолон', 'Pantolon siyah.'),
      w('бут кийим', 'ayakkabı', 'аяккабы', 'Ayakkabı yeni.'),
      w('куртка', 'ceket', 'жекет', 'Ceket giydim.'),
      w('калпак/шапка', 'şapka', 'шапка', 'Şapka aldım.'),
      w('байпак', 'çorap', 'чорап', 'Çorap nerede?'),
      w('сумка', 'çanta', 'чанта', 'Çantam ağır.'),
      w('саат', 'saat', 'саат', 'Saatim var.'),
      w('көз айнек', 'gözlük', 'гөзлүк', 'Gözlük takıyorum.'),
      w('кийүү', 'giymek', 'гиймэк', 'Ceket giyiyorum.'),
      w('чечүү', 'çıkarmak', 'чыкармак', 'Ayakkabımı çıkarıyorum.'),
    ],
  },
  {
    id: 'home',
    title: 'Үй жана буюмдар',
    icon: '🏠',
    words: [
      w('бөлмө', 'oda', 'ода', 'Odam temiz.'),
      w('эшик', 'kapı', 'капы', 'Kapı açık.'),
      w('терезе', 'pencere', 'пенжере', 'Pencere kapalı.'),
      w('стол', 'masa', 'маса', 'Masa büyük.'),
      w('отургуч', 'sandalye', 'сандалйе', 'Sandalye burada.'),
      w('керебет', 'yatak', 'ятак', 'Yatak rahat.'),
      w('ашкана', 'mutfak', 'мутфак', 'Mutfakta yemek var.'),
      w('ванна', 'banyo', 'банйо', 'Banyo temiz.'),
      w('ачкыч', 'anahtar', 'анахтар', 'Anahtar nerede?'),
      w('телефон', 'telefon', 'телефон', 'Telefon masada.'),
      w('компьютер', 'bilgisayar', 'билгисаяр', 'Bilgisayar çalışıyor.'),
      w('заряддагыч', 'şarj aleti', 'шарж алети', 'Şarj aleti lazım.'),
    ],
  },
  {
    id: 'technology',
    title: 'Технология',
    icon: '💻',
    words: [
      w('интернет', 'internet', 'интернет', 'İnternet var mı?'),
      w('сыр сөз', 'şifre', 'шифре', 'Şifre nedir?'),
      w('экран', 'ekran', 'экран', 'Ekran açık.'),
      w('баскыч', 'tuş', 'туш', 'Tuşa bas.'),
      w('файл', 'dosya', 'досйа', 'Dosyayı açtım.'),
      w('сайт', 'site', 'сите', 'Site çok güzel.'),
      w('тиркеме', 'uygulama', 'уйгулама', 'Uygulama çalışıyor.'),
      w('код', 'kod', 'код', 'Kod yazıyorum.'),
      w('жүктөө', 'indirmek', 'индирмек', 'Dosya indiriyorum.'),
      w('жиберүү', 'göndermek', 'гөндермек', 'Mesaj gönderdim.'),
      w('сактоо', 'kaydetmek', 'кайдетмек', 'Dosyayı kaydettim.'),
      w('өчүрүү', 'silmek', 'силмек', 'Mesajı sildim.'),
    ],
  },
  {
    id: 'emotions',
    title: 'Сезимдер',
    icon: '😊',
    words: [
      w('кубанычтуу', 'mutlu', 'мутлу', 'Bugün mutluyum.'),
      w('кайгылуу', 'üzgün', 'үзгүн', 'Biraz üzgünüm.'),
      w('чарчаган', 'yorgun', 'йоргун', 'Çok yorgunum.'),
      w('ачка', 'aç', 'ач', 'Açım, yemek istiyorum.'),
      w('суусаган', 'susamış', 'сусамыш', 'Susadım.'),
      w('корккон', 'korkmuş', 'коркмуш', 'Korkmuş değilim.'),
      w('таң калган', 'şaşırmış', 'шашырмыш', 'Çok şaşırdım.'),
      w('тынч', 'sakin', 'сакин', 'Sakin ol.'),
      w('шашылган', 'aceleci', 'ажележи', 'Acele etme.'),
      w('кызыккан', 'meraklı', 'мераклы', 'Meraklı bir öğrenciyim.'),
      w('ишенимдүү', 'emin', 'эмин', 'Emin misin?'),
      w('даяр', 'hazır', 'хазыр', 'Hazırım.'),
    ],
  },
  {
    id: 'classroom-commands',
    title: 'Класстагы сөздөр',
    icon: '📖',
    words: [
      w('ук', 'dinle', 'динле', 'Öğretmeni dinle.'),
      w('кайтала', 'tekrar et', 'текрар эт', 'Lütfen tekrar et.'),
      w('окуп бер', 'oku', 'оку', 'Cümleyi oku.'),
      w('жаз', 'yaz', 'яз', 'Deftere yaz.'),
      w('жооп бер', 'cevap ver', 'жевап вер', 'Soruyu cevapla.'),
      w('суроо бер', 'soru sor', 'сору сор', 'Soru sorabilirsin.'),
      w('ач', 'aç', 'ач', 'Kitabı aç.'),
      w('жап', 'kapat', 'капат', 'Defteri kapat.'),
      w('тур', 'kalk', 'калк', 'Ayağa kalk.'),
      w('отур', 'otur', 'отур', 'Lütfen otur.'),
      w('түшүндүр', 'açıkla', 'ачыкла', 'Bunu açıkla.'),
      w('текшер', 'kontrol et', 'контрол эт', 'Cevabını kontrol et.'),
    ],
  },
  {
    id: 'questions',
    title: 'Суроо түзүү',
    icon: '❓',
    words: [
      w('Ким?', 'Kim?', 'ким', 'Bu kim?'),
      w('Эмне?', 'Ne?', 'не', 'Bu ne?'),
      w('Кайда?', 'Nerede?', 'нереде', 'Ev nerede?'),
      w('Качан?', 'Ne zaman?', 'не заман', 'Ders ne zaman?'),
      w('Кантип?', 'Nasıl?', 'насыл', 'Nasıl gidiyorsun?'),
      w('Эмне үчүн?', 'Neden?', 'неден', 'Neden bekliyorsun?'),
      w('Канча?', 'Ne kadar?', 'не кадар', 'Bu ne kadar?'),
      w('Кайсы?', 'Hangi?', 'ханги', 'Hangi kitap?'),
      w('Кимдики?', 'Kimin?', 'кимин', 'Bu kimin?'),
      w('Барбы?', 'Var mı?', 'вар мы', 'Kalem var mı?'),
      w('Болобу?', 'Olur mu?', 'олур му', 'Bugün olur mu?'),
      w('Даярсыңбы?', 'Hazır mısın?', 'хазыр мысын', 'Hazır mısın?'),
    ],
  },
  {
    id: 'connectors',
    title: 'Байламталар',
    icon: '🔗',
    words: [
      w('жана', 've', 'ве', 'Ben ve sen.'),
      w('бирок', 'ama', 'ама', 'Gelmek istiyorum ama geç.'),
      w('анткени', 'çünkü', 'чүнки', 'Gelmedim çünkü hastaydım.'),
      w('ошондуктан', 'bu yüzden', 'бу йүзден', 'Bu yüzden çalışıyorum.'),
      w('эгер', 'eğer', 'ээр', 'Eğer istersen gel.'),
      w('дагы', 'de / da', 'де / да', 'Ben de geliyorum.'),
      w('же', 'veya', 'вея', 'Çay veya su.'),
      w('менен', 'ile', 'иле', 'Arkadaşımla geldim.'),
      w('үчүн', 'için', 'ичин', 'Senin için yaptım.'),
      w('кийин', 'sonra', 'сонра', 'Dersten sonra gel.'),
      w('мурун', 'önce', 'өнже', 'Dersten önce oku.'),
      w('ошондой эле', 'ayrıca', 'айрыжа', 'Ayrıca Türkçe öğreniyorum.'),
    ],
  },
  {
    id: 'colors',
    title: 'Түстөр',
    icon: '🎨',
    words: [
      w('ак', 'beyaz', 'беяз', 'Beyaz gömlek giydim.'),
      w('кара', 'siyah', 'сиях', 'Siyah çanta aldım.'),
      w('кызыл', 'kırmızı', 'кырмызы', 'Kırmızı kalem nerede?'),
      w('көк', 'mavi', 'мави', 'Mavi renk güzel.'),
      w('жашыл', 'yeşil', 'йешил', 'Yeşil ağaç var.'),
      w('сары', 'sarı', 'сары', 'Sarı araba gördüm.'),
      w('күрөң', 'kahverengi', 'кахверенги', 'Kahverengi masa.'),
      w('кызгылт', 'pembe', 'пембе', 'Pembe çiçek.'),
      w('кызгылт сары', 'turuncu', 'турунжу', 'Turuncu defter aldım.'),
      w('күлгүн', 'mor', 'мор', 'Mor renk seviyorum.'),
      w('боз', 'gri', 'гри', 'Gri hava.'),
      w('алтын түстүү', 'altın rengi', 'алтын ренги', 'Altın rengi saat.'),
    ],
  },
  {
    id: 'calendar',
    title: 'Айлар жана күндөр',
    icon: '📅',
    words: [
      w('дүйшөмбү', 'pazartesi', 'пазартеcи', 'Pazartesi ders var.'),
      w('шейшемби', 'salı', 'салы', 'Salı günü geliyorum.'),
      w('шаршемби', 'çarşamba', 'чаршамба', 'Çarşamba sınav var.'),
      w('бейшемби', 'perşembe', 'першембе', 'Perşembe boşum.'),
      w('жума', 'cuma', 'жума', 'Cuma namazı var.'),
      w('ишемби', 'cumartesi', 'жумартеси', 'Cumartesi çalışıyorum.'),
      w('жекшемби', 'pazar', 'пазар', 'Pazar dinleniyorum.'),
      w('январь', 'ocak', 'ожак', 'Ocak ayı soğuk.'),
      w('февраль', 'şubat', 'шубат', 'Şubat kısa bir ay.'),
      w('март', 'mart', 'март', 'Mart ayında bahar gelir.'),
      w('апрель', 'nisan', 'нисан', 'Nisan ayında yağmur yağar.'),
      w('май', 'mayıs', 'майыс', 'Mayıs güzel bir ay.'),
      w('июнь', 'haziran', 'хазиран', 'Haziran ayında tatil başlar.'),
      w('июль', 'temmuz', 'теммуз', 'Temmuz sıcak olur.'),
      w('август', 'ağustos', 'аустос', 'Ağustos ayında köye gidiyorum.'),
      w('сентябрь', 'eylül', 'эйлүл', 'Eylül ayında okul başlar.'),
      w('октябрь', 'ekim', 'эким', 'Ekim ayında hava serin.'),
      w('ноябрь', 'kasım', 'касым', 'Kasım ayında yağmur var.'),
      w('декабрь', 'aralık', 'аралык', 'Aralık ayında kar yağar.'),
    ],
  },
  {
    id: 'restaurant',
    title: 'Ресторан жана кафе',
    icon: '🍴',
    words: [
      w('меню', 'menü', 'менү', 'Menü alabilir miyim?'),
      w('заказ берүү', 'sipariş vermek', 'сипариш вермек', 'Sipariş vermek istiyorum.'),
      w('эсеп', 'hesap', 'хесап', 'Hesap alabilir miyiz?'),
      w('официант', 'garson', 'гарсон', 'Garson burada.'),
      w('даамдуу', 'lezzetli', 'леззетли', 'Yemek çok lezzetli.'),
      w('ачуу', 'acı', 'ажы', 'Bu yemek acı mı?'),
      w('таттуу', 'tatlı', 'татлы', 'Tatlı ister misin?'),
      w('туздуу', 'tuzlu', 'тузлу', 'Çorba biraz tuzlu.'),
      w('суусундук', 'içecek', 'ичежек', 'İçecek ne alırsınız?'),
      w('эртең мененки тамак', 'kahvaltı', 'кахвалты', 'Kahvaltı hazır.'),
      w('түшкү тамак', 'öğle yemeği', 'өле йемеи', 'Öğle yemeği yedim.'),
      w('кечки тамак', 'akşam yemeği', 'акшам йемеи', 'Akşam yemeği saat kaçta?'),
    ],
  },
  {
    id: 'travel',
    title: 'Саякат',
    icon: '🧳',
    words: [
      w('саякат', 'seyahat', 'сейахат', 'Seyahat etmeyi seviyorum.'),
      w('чемодан', 'valiz', 'вализ', 'Valizim ağır.'),
      w('паспорт', 'pasaport', 'пасапорт', 'Pasaportum yanımda.'),
      w('мейманкана', 'otel', 'отел', 'Otel nerede?'),
      w('бронь', 'rezervasyon', 'резервасйон', 'Rezervasyon yaptım.'),
      w('аэропорт', 'havaalanı', 'хавааланы', 'Havaalanına gidiyorum.'),
      w('учуу', 'uçuş', 'учуш', 'Uçuş saat kaçta?'),
      w('келүү', 'varış', 'варыш', 'Varış saati nedir?'),
      w('кетүү', 'kalkış', 'калкыш', 'Kalkış kapısı nerede?'),
      w('карта', 'harita', 'харита', 'Haritaya bakıyorum.'),
      w('эс алуу', 'tatil', 'татил', 'Tatile gidiyorum.'),
      w('турист', 'turist', 'турист', 'Turist yolu sordu.'),
    ],
  },
  {
    id: 'sports',
    title: 'Спорт',
    icon: '⚽',
    words: [
      w('спорт', 'spor', 'спор', 'Spor yapıyorum.'),
      w('футбол', 'futbol', 'футбол', 'Futbol oynuyoruz.'),
      w('баскетбол', 'basketbol', 'баскетбол', 'Basketbol seviyorum.'),
      w('волейбол', 'voleybol', 'волейбол', 'Voleybol takımı var.'),
      w('чуркоо', 'koşmak', 'кошмак', 'Her sabah koşuyorum.'),
      w('сүзүү', 'yüzmek', 'йүзмек', 'Yüzmeyi öğreniyorum.'),
      w('машыгуу', 'antrenman', 'антренман', 'Bugün antrenman var.'),
      w('команда', 'takım', 'такым', 'Takımımız kazandı.'),
      w('оюн', 'maç', 'мач', 'Maç başladı.'),
      w('утуу', 'kazanmak', 'казанмак', 'Maçı kazandık.'),
      w('утулуу', 'kaybetmek', 'кайбетмек', 'Maçı kaybettik.'),
      w('эреже', 'kural', 'курал', 'Kuralları biliyorum.'),
    ],
  },
  {
    id: 'nature',
    title: 'Табият',
    icon: '🌿',
    words: [
      w('табият', 'doğa', 'доа', 'Doğa çok güzel.'),
      w('тоо', 'dağ', 'даа', 'Dağa çıkıyoruz.'),
      w('дарыя', 'nehir', 'нехир', 'Nehir uzun.'),
      w('көл', 'göl', 'гөл', 'Göl kenarında oturduk.'),
      w('токой', 'orman', 'орман', 'Ormanda yürüdük.'),
      w('дарак', 'ağaç', 'аач', 'Ağaç yeşil.'),
      w('гүл', 'çiçek', 'чичек', 'Çiçek çok güzel.'),
      w('жер', 'yer', 'йер', 'Yer temiz.'),
      w('асман', 'gökyüzü', 'гөкйүзү', 'Gökyüzü mavi.'),
      w('күн', 'güneş', 'гүнеш', 'Güneş parlıyor.'),
      w('ай', 'ay', 'ай', 'Ay görünüyor.'),
      w('жылдыз', 'yıldız', 'йылдыз', 'Yıldızlar parlak.'),
    ],
  },
  {
    id: 'animals',
    title: 'Жаныбарлар',
    icon: '🐾',
    words: [
      w('мышык', 'kedi', 'кеди', 'Kedi uyuyor.'),
      w('ит', 'köpek', 'көпек', 'Köpek koşuyor.'),
      w('ат', 'at', 'ат', 'At hızlı koşar.'),
      w('уй', 'inek', 'инек', 'İnek süt verir.'),
      w('кой', 'koyun', 'койун', 'Koyun ot yiyor.'),
      w('эчки', 'keçi', 'кечи', 'Keçi dağda.'),
      w('куш', 'kuş', 'куш', 'Kuş uçuyor.'),
      w('балык', 'balık', 'балык', 'Balık suda yaşar.'),
      w('коён', 'tavşan', 'тавшан', 'Tavşan hızlı.'),
      w('арстан', 'aslan', 'аслан', 'Aslan güçlü.'),
      w('аюу', 'ayı', 'айы', 'Ayı ormanda.'),
      w('түлкү', 'tilki', 'тилки', 'Tilki kurnaz.'),
    ],
  },
  {
    id: 'bank',
    title: 'Банк жана төлөм',
    icon: '🏦',
    words: [
      w('банк', 'banka', 'банка', 'Bankaya gidiyorum.'),
      w('эсеп', 'hesap', 'хесап', 'Hesap açmak istiyorum.'),
      w('карыз', 'borç', 'борч', 'Borç almak istemiyorum.'),
      w('насыя', 'kredi', 'креди', 'Kredi başvurusu yaptım.'),
      w('төлөм', 'ödeme', 'өдеме', 'Ödeme yaptım.'),
      w('акча которуу', 'para göndermek', 'пара гөндермек', 'Para göndermek istiyorum.'),
      w('акча алуу', 'para çekmek', 'пара чекмек', 'Bankamatikten para çektim.'),
      w('банк карта', 'banka kartı', 'банка карты', 'Banka kartım kayboldu.'),
      w('купуя сөз', 'şifre', 'шифре', 'Şifremi unuttum.'),
      w('квитанция', 'makbuz', 'макбуз', 'Makbuz alabilir miyim?'),
      w('банкомат', 'bankamatik', 'банкаматик', 'Bankamatik nerede?'),
      w('валюта', 'döviz', 'дөвиз', 'Döviz kuru nedir?'),
    ],
  },
  {
    id: 'city-services',
    title: 'Шаар кызматтары',
    icon: '🏙️',
    words: [
      w('почта', 'posta', 'поста', 'Posta nerede?'),
      w('полиция', 'polis', 'полис', 'Polisi arayın.'),
      w('өрт өчүрүү кызматы', 'itfaiye', 'итфайе', 'İtfaiye geldi.'),
      w('тез жардам', 'ambulans', 'амбуланс', 'Ambulans çağırın.'),
      w('муниципалитет', 'belediye', 'беледийе', 'Belediyeye gittim.'),
      w('парк', 'park', 'парк', 'Parkta yürüdük.'),
      w('музей', 'müze', 'мүзе', 'Müzeye gittik.'),
      w('кинотеатр', 'sinema', 'синема', 'Sinemaya gidelim.'),
      w('аптека', 'eczane', 'эжзане', 'Eczane açık mı?'),
      w('станция', 'istasyon', 'истасйон', 'İstasyon nerede?'),
      w('коомдук транспорт', 'toplu taşıma', 'топлу ташыма', 'Toplu taşıma kullanıyorum.'),
      w('аянт', 'meydan', 'мейдан', 'Meydan kalabalık.'),
    ],
  },
  {
    id: 'work',
    title: 'Жумуш',
    icon: '💼',
    words: [
      w('жумуш', 'iş', 'иш', 'İşe gidiyorum.'),
      w('кеңсе', 'ofis', 'офис', 'Ofiste çalışıyorum.'),
      w('жолугушуу', 'toplantı', 'топланты', 'Toplantı saat ikide.'),
      w('долбоор', 'proje', 'проже', 'Yeni proje başladı.'),
      w('тапшырма', 'görev', 'гөрев', 'Görevimi bitirdim.'),
      w('команда', 'ekip', 'экип', 'Ekiple çalışıyorum.'),
      w('жетекчи', 'yönetici', 'йөнетижи', 'Yönetici geldi.'),
      w('тажрыйба', 'deneyim', 'денейим', 'Deneyim kazandım.'),
      w('эмгек акы', 'maaş', 'мааш', 'Maaş ne zaman?'),
      w('эс алуу күнү', 'izin', 'изин', 'Bugün izinliyim.'),
      w('резюме', 'özgeçmiş', 'өзгечмиш', 'Özgeçmiş hazırladım.'),
      w('маек', 'mülakat', 'мүлакат', 'Mülakata gideceğim.'),
    ],
  },
  {
    id: 'internet-chat',
    title: 'Интернет сүйлөшүү',
    icon: '📱',
    words: [
      w('билдирүү', 'mesaj', 'месаж', 'Mesaj gönderdim.'),
      w('чалуу', 'aramak', 'арамак', 'Seni arayacağım.'),
      w('жооп жазуу', 'cevap yazmak', 'жевап язмак', 'Mesaja cevap yazdım.'),
      w('сүрөт', 'fotoğraf', 'фотораф', 'Fotoğraf gönderdim.'),
      w('видео', 'video', 'видео', 'Video izliyorum.'),
      w('үн билдирүү', 'sesli mesaj', 'сесли месаж', 'Sesli mesaj attım.'),
      w('онлайн', 'çevrim içi', 'чеврим ичи', 'Çevrim içi misin?'),
      w('оффлайн', 'çevrim dışı', 'чеврим дышы', 'Şu an çevrim dışı.'),
      w('группа', 'grup', 'груп', 'Gruba mesaj yazdım.'),
      w('катталуу', 'kayıt olmak', 'кайыт олмак', 'Siteye kayıt oldum.'),
      w('кирүү', 'giriş yapmak', 'гириш япмак', 'Hesabıma giriş yaptım.'),
      w('чыгуу', 'çıkış yapmak', 'чыкыш япмак', 'Hesaptan çıkış yaptım.'),
    ],
  },
  {
    id: 'personality',
    title: 'Мүнөз',
    icon: '🌟',
    words: [
      w('акылдуу', 'akıllı', 'акыллы', 'Akıllı bir öğrenci.'),
      w('эмгекчил', 'çalışkan', 'чалышкан', 'Çalışkan insan başarılı olur.'),
      w('жалкоо', 'tembel', 'тембел', 'Tembel olmak istemiyorum.'),
      w('чынчыл', 'dürüst', 'дүрүст', 'Dürüst olmak önemlidir.'),
      w('боорукер', 'merhametli', 'мерхаметли', 'Merhametli bir insan.'),
      w('тынч', 'sakin', 'сакин', 'Sakin kal.'),
      w('шайыр', 'neşeli', 'нешели', 'Neşeli görünüyorsun.'),
      w('кайраттуу', 'cesur', 'жесур', 'Cesur ol.'),
      w('жоопкерчиликтүү', 'sorumlu', 'сорумлу', 'Sorumlu bir öğrenciyim.'),
      w('сабырдуу', 'sabırlı', 'сабырлы', 'Sabırlı olmalısın.'),
      w('сылык', 'kibar', 'кибар', 'Kibar konuş.'),
      w('тамашакөй', 'şakacı', 'шакаджы', 'Şakacı bir arkadaşım var.'),
    ],
  },
  {
    id: 'education-advanced',
    title: 'Окуу процесси',
    icon: '🎓',
    words: [
      w('билим', 'bilgi', 'билги', 'Bilgi güçtür.'),
      w('тема', 'konu', 'кону', 'Bugünkü konu kolay.'),
      w('максат', 'hedef', 'хедеф', 'Hedefim Türkçe konuşmak.'),
      w('натыйжа', 'sonuç', 'сонуч', 'Sonuç iyi oldu.'),
      w('текшерүү', 'kontrol', 'контрол', 'Kontrol zamanı.'),
      w('көнүгүү', 'alıştırma', 'алыштырма', 'Alıştırma yapıyorum.'),
      w('мисал', 'örnek', 'өрнек', 'Bir örnek ver.'),
      w('сөздүк', 'sözlük', 'сөзлүк', 'Sözlük kullanıyorum.'),
      w('котормо', 'çeviri', 'чевири', 'Çeviri yaptım.'),
      w('айтылыш', 'telaffuz', 'телаффуз', 'Telaffuzum gelişiyor.'),
      w('эреже', 'kural', 'курал', 'Kuralı öğrendim.'),
      w('сабак планы', 'ders planı', 'дерс планы', 'Ders planı hazır.'),
    ],
  },
  {
    id: 'ready-sentences',
    title: 'Даяр сүйлөмдөр',
    icon: '✅',
    words: [
      w('Мен бүгүн бош эмесмин', 'Bugün müsait değilim', 'бүгүн мүсаит деилим', 'Bugün müsait değilim.'),
      w('Мен сага кийин жазам', 'Sana sonra yazarım', 'сана сонра язарыm', 'Sana sonra yazarım.'),
      w('Мен азыр келем', 'Şimdi geliyorum', 'шимди гелийорум', 'Şimdi geliyorum.'),
      w('Күтүп тур', 'Bekle', 'бекле', 'Bir dakika bekle.'),
      w('Мен даярмын', 'Hazırım', 'хазырым', 'Hazırım, başlayalım.'),
      w('Кайдан келдиң?', 'Nereden geldin?', 'нереден гелдин', 'Nereden geldin?'),
      w('Кайда барасың?', 'Nereye gidiyorsun?', 'нерейе гидийорсун', 'Nereye gidiyorsun?'),
      w('Сен эмне кылып жатасың?', 'Ne yapıyorsun?', 'не япыйорсун', 'Ne yapıyorsun?'),
      w('Мен сабак окуп жатам', 'Ders çalışıyorum', 'дерс чалышыйорум', 'Ders çalışıyorum.'),
      w('Бүгүн аба ырайы жакшы', 'Bugün hava güzel', 'бүгүн хава гүзел', 'Bugün hava güzel.'),
      w('Мен сени түшүндүм', 'Seni anladım', 'сени анладым', 'Seni anladım.'),
      w('Кайра жолугабыз', 'Tekrar görüşürüz', 'текрар гөрүшүрүз', 'Tekrar görüşürüz.'),
    ],
  },
  {
    id: 'opinion',
    title: 'Ой билдирүү',
    icon: '💡',
    words: [
      w('менимче', 'bence', 'бенже', 'Bence bu doğru.'),
      w('сенинче', 'sence', 'сенже', 'Sence nasıl?'),
      w('мен ойлойм', 'düşünüyorum', 'дүшүнүйорум', 'Böyle düşünüyorum.'),
      w('мен билем', 'biliyorum', 'билийорум', 'Bunu biliyorum.'),
      w('мен билбейм', 'bilmiyorum', 'билмийорум', 'Bilmiyorum.'),
      w('мүмкүн', 'belki', 'белки', 'Belki yarın gelir.'),
      w('албетте', 'elbette', 'элбетте', 'Elbette yardım ederim.'),
      w('чын эле', 'gerçekten', 'герчектен', 'Gerçekten güzel.'),
      w('туура', 'doğru', 'доору', 'Bu doğru.'),
      w('туура эмес', 'yanlış', 'ялыш', 'Bu yanlış.'),
      w('керемет', 'harika', 'харика', 'Harika bir fikir.'),
      w('маанилүү', 'önemli', 'өнемли', 'Bu çok önemli.'),
    ],
  },
  {
    id: 'time-advanced',
    title: 'Убакыт фразалары',
    icon: '⌛',
    words: [
      w('эрте', 'erken', 'эркен', 'Erken geldim.'),
      w('кеч', 'geç', 'геч', 'Geç kaldım.'),
      w('дароо', 'hemen', 'хемен', 'Hemen geliyorum.'),
      w('азырынча', 'şimdilik', 'шимдилик', 'Şimdilik bu kadar.'),
      w('кээде', 'bazen', 'базен', 'Bazen kitap okurum.'),
      w('ар дайым', 'her zaman', 'хер заман', 'Her zaman çalışıyorum.'),
      w('эч качан', 'asla', 'асла', 'Asla vazgeçme.'),
      w('көбүнчө', 'genellikle', 'генелликле', 'Genellikle erken kalkarım.'),
      w('бир аздан кийин', 'biraz sonra', 'бираз сонра', 'Biraz sonra görüşürüz.'),
      w('өткөн жылы', 'geçen yıl', 'гечен йыл', 'Geçen yıl mezun oldum.'),
      w('кийинки апта', 'gelecek hafta', 'гележеk хафта', 'Gelecek hafta sınav var.'),
      w('ушул ай', 'bu ay', 'бу ай', 'Bu ay çok çalıştım.'),
    ],
  },
  {
    id: 'emergency',
    title: 'Шашылыш учур',
    icon: '🚨',
    words: [
      w('жардам!', 'yardım!', 'ярдым', 'Yardım edin!'),
      w('кооптуу', 'tehlikeli', 'техликели', 'Burası tehlikeli.'),
      w('жоголуп кеттим', 'kayboldum', 'кайболдум', 'Kayboldum, yardım eder misiniz?'),
      w('чалыңыз', 'arayın', 'арайын', 'Lütfen polisi arayın.'),
      w('токтоңуз', 'durun', 'дурун', 'Lütfen durun.'),
      w('мени менен келиңиз', 'benimle gelin', 'бенимле гелин', 'Benimle gelin.'),
      w('мен ооруп жатам', 'hastayım', 'хастайым', 'Hastayım, doktora gitmeliyim.'),
      w('капчыгым жоголду', 'cüzdanım kayboldu', 'жүзданым кайболду', 'Cüzdanım kayboldu.'),
      w('телефонум жоголду', 'telefonum kayboldu', 'телефонум кайболду', 'Telefonum kayboldu.'),
      w('дарек', 'adres', 'адрес', 'Adresinizi yazar mısınız?'),
      w('коопсуз', 'güvenli', 'гүвенли', 'Burası güvenli.'),
      w('тез', 'çabuk', 'чабук', 'Çabuk gelin!'),
    ],
  },
  {
    id: 'village-city',
    title: 'Айыл жана шаар',
    icon: '🏘️',
    words: [
      w('район', 'ilçe', 'илче', 'İlçede yaşıyorum.'),
      w('облус', 'bölge', 'бөлге', 'Bu bölge güzel.'),
      w('борбор', 'merkez', 'меркез', 'Merkeze gidiyorum.'),
      w('көпүрө', 'köprü', 'көпүрү', 'Köprüden geçtik.'),
      w('имарат', 'bina', 'бина', 'Bina yüksek.'),
      w('бакча', 'bahçe', 'бахче', 'Bahçede çiçek var.'),
      w('короо', 'avlu', 'авлу', 'Avluda çocuklar var.'),
      w('коңшу', 'komşu', 'комшу', 'Komşumuz iyi.'),
      w('жергиликтүү', 'yerel', 'йерел', 'Yerel halk yardım etti.'),
      w('эл', 'halk', 'халк', 'Halk burada toplandı.'),
      w('конок', 'misafir', 'мисафир', 'Misafir geldi.'),
      w('той', 'düğün', 'дүгүн', 'Düğüne gidiyoruz.'),
    ],
  },
  {
    id: 'kitchen',
    title: 'Ашкана буюмдары',
    icon: '🥄',
    words: [
      w('табак', 'tabak', 'табак', 'Tabak masada.'),
      w('кашык', 'kaşık', 'кашык', 'Kaşık nerede?'),
      w('айры', 'çatal', 'чатал', 'Çatal lazım.'),
      w('бычак', 'bıçak', 'бычак', 'Bıçak keskin.'),
      w('казан', 'tencere', 'тенжере', 'Tencere ocakta.'),
      w('чайнек', 'çaydanlık', 'чайданлык', 'Çaydanlık sıcak.'),
      w('чыны', 'bardak', 'бардак', 'Bardak temiz.'),
      w('муздаткыч', 'buzdolabı', 'буздолабы', 'Buzdolabı dolu.'),
      w('меш', 'fırın', 'фырын', 'Fırında ekmek var.'),
      w('плита', 'ocak', 'ожак', 'Ocak açık.'),
      w('салфетка', 'peçete', 'печете', 'Peçete alabilir miyim?'),
      w('тазалоо', 'temizlemek', 'темизлемек', 'Mutfağı temizledim.'),
    ],
  },
  {
    id: 'hobbies',
    title: 'Хобби',
    icon: '🎯',
    words: [
      w('хобби', 'hobi', 'хоби', 'Hobin nedir?'),
      w('китеп окуу', 'kitap okumak', 'китап окумак', 'Kitap okumayı seviyorum.'),
      w('музыка угуу', 'müzik dinlemek', 'мүзик динлемек', 'Müzik dinliyorum.'),
      w('сүрөт тартуу', 'resim çizmek', 'ресим чизмек', 'Resim çiziyorum.'),
      w('бийлөө', 'dans etmek', 'данс этмек', 'Dans etmeyi seviyorum.'),
      w('ырдоо', 'şarkı söylemek', 'шаркы сойлемек', 'Şarkı söylüyorum.'),
      w('оюн ойноо', 'oyun oynamak', 'оюн ойнамак', 'Oyun oynamıyorum.'),
      w('тамак жасоо', 'yemek yapmak', 'йемек япмак', 'Yemek yapıyorum.'),
      w('сейилдөө', 'gezmek', 'гезмек', 'Parkta geziyorum.'),
      w('сүрөткө тартуу', 'fotoğraf çekmek', 'фотораф чекмек', 'Fotoğraf çekiyorum.'),
      w('код жазуу', 'kod yazmak', 'код язмак', 'Kod yazmayı seviyorum.'),
      w('үйрөнүү', 'öğrenmek', 'өөренмек', 'Yeni şeyler öğreniyorum.'),
    ],
  },
  {
    id: 'communication-politeness',
    title: 'Сылык сүйлөө',
    icon: '🤝',
    words: [
      w('уруксатпы?', 'müsaade eder misiniz?', 'мүсааде эдер мисиниз', 'Müsaade eder misiniz?'),
      w('кирсем болобу?', 'girebilir miyim?', 'гиребилир мийим', 'İçeri girebilir miyim?'),
      w('отурсам болобу?', 'oturabilir miyim?', 'отурабилир мийим', 'Buraya oturabilir miyim?'),
      w('алсам болобу?', 'alabilir miyim?', 'алабилир мийим', 'Bunu alabilir miyim?'),
      w('сүйлөсөм болобу?', 'konuşabilir miyim?', 'конушабилир мийим', 'Sizinle konuşabilir miyim?'),
      w('карап көрүңүзчү', 'bakar mısınız?', 'бакар мысыныз', 'Bakar mısınız?'),
      w('күтө туруңузчу', 'bekler misiniz?', 'беклер мисиниз', 'Biraz bekler misiniz?'),
      w('кайталап коюңузчу', 'tekrarlar mısınız?', 'текрарлар мысыныз', 'Tekrarlar mısınız?'),
      w('кечигип калдым', 'geç kaldım', 'геч калдым', 'Özür dilerim, geç kaldım.'),
      w('уруксат бериңиз', 'izin verin', 'изин верин', 'Lütfen izin verin.'),
      w('мен ыраазымын', 'memnunum', 'мемнунум', 'Yardımınızdan memnunum.'),
      w('сизге ийгилик', 'başarılar', 'башарылар', 'Size başarılar dilerim.'),
    ],
  },
];

export const allWords = wordCategories.flatMap((category) =>
  category.words.map((word) => ({ ...word, category: category.title }))
);
