export interface EnglishWord {
  ky: string;
  en: string;
  reading: string;
  example: string;
}

export interface WordCategory {
  id: string;
  title: string;
  icon: string;
  words: EnglishWord[];
}

export const alphabet = [
  { letter: 'A', sound: 'эй', example: 'apple - алма' },
  { letter: 'B', sound: 'би', example: 'book - китеп' },
  { letter: 'C', sound: 'си', example: 'cat - мышык' },
  { letter: 'D', sound: 'ди', example: 'door - эшик' },
  { letter: 'E', sound: 'и', example: 'egg - жумуртка' },
  { letter: 'F', sound: 'эф', example: 'fish - балык' },
  { letter: 'G', sound: 'жи', example: 'green - жашыл' },
  { letter: 'H', sound: 'эйч', example: 'house - үй' },
  { letter: 'I', sound: 'ай', example: 'ice - муз' },
  { letter: 'J', sound: 'жей', example: 'job - жумуш' },
  { letter: 'K', sound: 'кей', example: 'key - ачкыч' },
  { letter: 'L', sound: 'эл', example: 'lesson - сабак' },
  { letter: 'M', sound: 'эм', example: 'mother - апа' },
  { letter: 'N', sound: 'эн', example: 'name - ат' },
  { letter: 'O', sound: 'оу', example: 'open - ачуу' },
  { letter: 'P', sound: 'пи', example: 'pen - калем' },
  { letter: 'Q', sound: 'кью', example: 'question - суроо' },
  { letter: 'R', sound: 'ар', example: 'red - кызыл' },
  { letter: 'S', sound: 'эс', example: 'school - мектеп' },
  { letter: 'T', sound: 'ти', example: 'teacher - мугалим' },
  { letter: 'U', sound: 'ю', example: 'use - колдонуу' },
  { letter: 'V', sound: 'ви', example: 'voice - үн' },
  { letter: 'W', sound: 'дабл ю', example: 'water - суу' },
  { letter: 'X', sound: 'экс', example: 'box - куту' },
  { letter: 'Y', sound: 'уай', example: 'yes - ооба' },
  { letter: 'Z', sound: 'зед', example: 'zero - нөл' },
];

export const grammarTopics = [
  {
    title: 'I, you, he, she',
    rule: 'Адам ат атоочтору: I - мен, you - сен/сиз, he - ал эркек, she - ал кыз, we - биз, they - алар.',
    example: 'I am a student. - Мен окуучумун.',
  },
  {
    title: 'To be: am / is / are',
    rule: 'Англисче “болуу” үчүн am, is, are колдонулат.',
    example: 'She is my teacher. - Ал менин мугалимим.',
  },
  {
    title: 'Суроо түзүү',
    rule: 'Көп суроолордо жардамчы сөз алдыга чыгат: do, does, is, are.',
    example: 'Do you speak English? - Сен англисче сүйлөйсүңбү?',
  },
  {
    title: 'Азыркы чак',
    rule: 'Күнүмдүк иштер үчүн Present Simple колдонулат.',
    example: 'I study every day. - Мен күн сайын окуйм.',
  },
  {
    title: 'Азыр болуп жаткан иш',
    rule: 'am/is/are + -ing формасы колдонулат.',
    example: 'I am learning English. - Мен англисче үйрөнүп жатам.',
  },
  {
    title: 'Каалоо: want to',
    rule: 'Бир нерсе кылгың келсе “want to” колдонулат.',
    example: 'I want to speak English. - Мен англисче сүйлөгүм келет.',
  },
  {
    title: 'Керек: need to',
    rule: 'Керек болгон ишти айтуу үчүн “need to” колдонулат.',
    example: 'I need to practice. - Мен машыгышым керек.',
  },
  {
    title: 'Өткөн чак',
    rule: 'Жөнөкөй өткөн чакта көп этиштерге -ed кошулат, бирок irregular verbs өзүнчө өзгөрөт.',
    example: 'I learned new words. - Мен жаңы сөздөрдү үйрөндүм.',
  },
];

export const dialogs = [
  {
    title: 'Таанышуу',
    lines: [
      ['Hello!', 'Салам!'],
      ['What is your name?', 'Атың ким?'],
      ['My name is Aybek.', 'Менин атым Айбек.'],
      ['Nice to meet you.', 'Таанышканыма кубанычтамын.'],
    ],
  },
  {
    title: 'Мектепте',
    lines: [
      ['When does the lesson start?', 'Сабак качан башталат?'],
      ['The lesson starts at eight.', 'Сабак саат сегизде башталат.'],
      ['Do you have a book?', 'Китебиң барбы?'],
      ['Yes, I have a book.', 'Ооба, китебим бар.'],
    ],
  },
  {
    title: 'Жол суроо',
    lines: [
      ['Excuse me, where is the school?', 'Кечиресиз, мектеп кайда?'],
      ['Go straight and turn right.', 'Түз барыңыз да оңго бурулуңуз.'],
      ['Is it far?', 'Алыспы?'],
      ['No, it is very close.', 'Жок, абдан жакын.'],
    ],
  },
  {
    title: 'Дүкөндө',
    lines: [
      ['How much is this?', 'Бул канча турат?'],
      ['It is fifty soms.', 'Бул элүү сом.'],
      ['Can I pay by card?', 'Карта менен төлөсөм болобу?'],
      ['Sure, no problem.', 'Албетте, маселе жок.'],
    ],
  },
  {
    title: 'Күнүмдүк сүйлөшүү',
    lines: [
      ['How are you today?', 'Бүгүн кандайсың?'],
      ['I am fine, thank you.', 'Жакшымын, рахмат.'],
      ['What are you doing?', 'Эмне кылып жатасың?'],
      ['I am studying English.', 'Мен англисче окуп жатам.'],
    ],
  },
];

const w = (ky: string, en: string, reading: string, example: string): EnglishWord => ({ ky, en, reading, example });

export const wordCategories: WordCategory[] = [
  {
    id: 'greetings',
    title: 'Саламдашуу',
    icon: '👋',
    words: [
      w('салам', 'hello', 'хеллоу', 'Hello, how are you?'),
      w('саламатсызбы', 'good morning', 'гуд морнинг', 'Good morning, teacher.'),
      w('кайырлуу күн', 'good afternoon', 'гуд афтернун', 'Good afternoon, everyone.'),
      w('кайырлуу кеч', 'good evening', 'гуд ивнинг', 'Good evening, my friend.'),
      w('кош бол', 'goodbye', 'гудбай', 'Goodbye, see you tomorrow.'),
      w('көрүшкөнчө', 'see you', 'си ю', 'See you later.'),
      w('кандайсың?', 'how are you?', 'хау ар ю', 'How are you today?'),
      w('жакшымын', 'I am fine', 'ай эм файн', 'I am fine, thank you.'),
      w('рахмат', 'thank you', 'сэнк ю', 'Thank you very much.'),
      w('суранам', 'please', 'плиз', 'Please help me.'),
      w('кечиресиз', 'excuse me', 'экскьюз ми', 'Excuse me, where is the library?'),
      w('макул', 'okay', 'оукей', 'Okay, I understand.'),
    ],
  },
  {
    id: 'speaking',
    title: 'Сүйлөө фразалары',
    icon: '🗣️',
    words: [
      w('Мен англисче үйрөнүп жатам', 'I am learning English', 'ай эм лернинг инглиш', 'I am learning English every day.'),
      w('Мен англисче аз сүйлөйм', 'I speak a little English', 'ай спик э литл инглиш', 'I speak a little English.'),
      w('Жай сүйлөңүзчү', 'Please speak slowly', 'плиз спик слоули', 'Please speak slowly.'),
      w('Кайра айтыңызчы', 'Please repeat', 'плиз рипит', 'Please repeat the sentence.'),
      w('Мен түшүндүм', 'I understand', 'ай андерстэнд', 'I understand you.'),
      w('Мен түшүнгөн жокмун', 'I do not understand', 'ай ду нот андерстэнд', 'I do not understand this word.'),
      w('Бул эмнени билдирет?', 'What does it mean?', 'уот даз ит мин', 'What does this word mean?'),
      w('Кантип айтылат?', 'How do you say it?', 'хау ду ю сей ит', 'How do you say it in English?'),
      w('Мага жардам керек', 'I need help', 'ай нид хелп', 'I need help with English.'),
      w('Мен аракет кылам', 'I will try', 'ай вил трай', 'I will try again.'),
      w('Мен даярмын', 'I am ready', 'ай эм реди', 'I am ready to answer.'),
      w('Мен сүйлөгүм келет', 'I want to speak', 'ай уонт ту спик', 'I want to speak English.'),
    ],
  },
  {
    id: 'school',
    title: 'Мектеп',
    icon: '🏫',
    words: [
      w('мектеп', 'school', 'скул', 'Our school is beautiful.'),
      w('окуучу', 'student', 'студент', 'I am a student.'),
      w('мугалим', 'teacher', 'тичер', 'The teacher is in the classroom.'),
      w('сабак', 'lesson', 'лесон', 'The lesson starts now.'),
      w('класс', 'classroom', 'классрум', 'The classroom is clean.'),
      w('китеп', 'book', 'бук', 'The book is on the table.'),
      w('дептер', 'notebook', 'ноутбук', 'My notebook is blue.'),
      w('калем', 'pen', 'пен', 'I have a pen.'),
      w('такта', 'board', 'борд', 'Write on the board.'),
      w('үй тапшырма', 'homework', 'хоумворк', 'I did my homework.'),
      w('экзамен', 'exam', 'игзэм', 'The exam is easy.'),
      w('баа', 'grade', 'грейд', 'My grade is good.'),
    ],
  },
  {
    id: 'family',
    title: 'Үй-бүлө',
    icon: '👨‍👩‍👧‍👦',
    words: [
      w('үй-бүлө', 'family', 'фэмили', 'My family is big.'),
      w('ата', 'father', 'фазер', 'My father works.'),
      w('апа', 'mother', 'мазер', 'My mother is kind.'),
      w('ага/ини', 'brother', 'бразер', 'My brother studies.'),
      w('эже/сиңди', 'sister', 'систер', 'My sister reads a book.'),
      w('чоң ата', 'grandfather', 'грэндфазер', 'My grandfather is at home.'),
      w('чоң апа', 'grandmother', 'грэндмазер', 'My grandmother cooks.'),
      w('дос', 'friend', 'френд', 'My friend is here.'),
      w('коңшу', 'neighbor', 'нейбор', 'Our neighbor is nice.'),
      w('бала', 'child', 'чайлд', 'The child is happy.'),
      w('ата-эне', 'parents', 'пэрентс', 'My parents help me.'),
      w('тууган', 'relative', 'релатив', 'My relative lives in Bishkek.'),
    ],
  },
  {
    id: 'numbers',
    title: 'Сандар',
    icon: '🔢',
    words: [
      w('нөл', 'zero', 'зиро', 'Zero mistakes.'),
      w('бир', 'one', 'уан', 'One book.'),
      w('эки', 'two', 'ту', 'Two pens.'),
      w('үч', 'three', 'сри', 'Three students.'),
      w('төрт', 'four', 'фор', 'Four chairs.'),
      w('беш', 'five', 'файв', 'Five lessons.'),
      w('алты', 'six', 'сикс', 'Six days.'),
      w('жети', 'seven', 'севен', 'Seven questions.'),
      w('сегиз', 'eight', 'эйт', 'Eight hours.'),
      w('тогуз', 'nine', 'найн', 'Nine words.'),
      w('он', 'ten', 'тен', 'Ten answers.'),
      w('жүз', 'hundred', 'хандред', 'One hundred points.'),
    ],
  },
  {
    id: 'daily',
    title: 'Күнүмдүк сөздөр',
    icon: '🧭',
    words: [
      w('ооба', 'yes', 'йес', 'Yes, I know.'),
      w('жок', 'no', 'ноу', 'No, I do not know.'),
      w('балким', 'maybe', 'мейби', 'Maybe tomorrow.'),
      w('азыр', 'now', 'нау', 'I am studying now.'),
      w('бүгүн', 'today', 'тудей', 'Today is Monday.'),
      w('эртең', 'tomorrow', 'тумороу', 'See you tomorrow.'),
      w('кечээ', 'yesterday', 'йестердей', 'Yesterday I was busy.'),
      w('бул', 'this', 'зис', 'This is my book.'),
      w('тигил', 'that', 'зэт', 'That is our school.'),
      w('бул жерде', 'here', 'хиер', 'Come here.'),
      w('ал жерде', 'there', 'зер', 'The bag is there.'),
      w('баары', 'everyone', 'эвриуан', 'Everyone is ready.'),
    ],
  },
  {
    id: 'questions',
    title: 'Суроо түзүү',
    icon: '❓',
    words: [
      w('Ким?', 'Who?', 'ху', 'Who is this?'),
      w('Эмне?', 'What?', 'уот', 'What is your name?'),
      w('Кайда?', 'Where?', 'уэа', 'Where do you live?'),
      w('Качан?', 'When?', 'уэн', 'When does the lesson start?'),
      w('Эмне үчүн?', 'Why?', 'уай', 'Why are you late?'),
      w('Кантип?', 'How?', 'хау', 'How are you?'),
      w('Канча?', 'How much?', 'хау мач', 'How much is this?'),
      w('Канча даана?', 'How many?', 'хау мени', 'How many books do you have?'),
      w('Кайсы?', 'Which?', 'уич', 'Which one is yours?'),
      w('Кимдики?', 'Whose?', 'хуз', 'Whose pen is this?'),
      w('Болобу?', 'Can I?', 'кэн ай', 'Can I ask a question?'),
      w('Сен даярсыңбы?', 'Are you ready?', 'ар ю реди', 'Are you ready?'),
    ],
  },
  {
    id: 'verbs',
    title: 'Этиштер',
    icon: '🏃',
    words: [
      w('баруу', 'go', 'гоу', 'I go to school.'),
      w('келүү', 'come', 'кам', 'Come here, please.'),
      w('окуу', 'read', 'рид', 'I read a book.'),
      w('жазуу', 'write', 'райт', 'Write your name.'),
      w('сүйлөө', 'speak', 'спик', 'I speak English.'),
      w('угуу', 'listen', 'лисн', 'Listen to me.'),
      w('көрүү', 'see', 'си', 'I see the board.'),
      w('билүү', 'know', 'ноу', 'I know this word.'),
      w('үйрөнүү', 'learn', 'лерн', 'I learn English.'),
      w('иштөө', 'work', 'ворк', 'My father works.'),
      w('жашоо', 'live', 'лив', 'I live in Kyrgyzstan.'),
      w('суроо', 'ask', 'аск', 'Ask a question.'),
      w('жооп берүү', 'answer', 'ансер', 'Answer the question.'),
      w('түшүнүү', 'understand', 'андерстэнд', 'I understand.'),
    ],
  },
  {
    id: 'food',
    title: 'Тамак-аш',
    icon: '🍽️',
    words: [
      w('суу', 'water', 'уотер', 'I drink water.'),
      w('чай', 'tea', 'ти', 'Tea is hot.'),
      w('нан', 'bread', 'бред', 'Bread is fresh.'),
      w('сүт', 'milk', 'милк', 'Milk is white.'),
      w('тамак', 'food', 'фуд', 'The food is ready.'),
      w('алма', 'apple', 'эпл', 'I eat an apple.'),
      w('банан', 'banana', 'банана', 'The banana is yellow.'),
      w('жумуртка', 'egg', 'эг', 'I want an egg.'),
      w('эт', 'meat', 'мит', 'Meat is expensive.'),
      w('шорпо', 'soup', 'суп', 'The soup is hot.'),
      w('күрүч', 'rice', 'райс', 'Rice is ready.'),
      w('кант', 'sugar', 'шугар', 'Sugar is sweet.'),
    ],
  },
  {
    id: 'places',
    title: 'Жерлер',
    icon: '📍',
    words: [
      w('үй', 'house', 'хаус', 'My house is small.'),
      w('айыл', 'village', 'вилиж', 'My village is beautiful.'),
      w('шаар', 'city', 'сити', 'The city is big.'),
      w('көчө', 'street', 'стрит', 'The street is clean.'),
      w('дүкөн', 'shop', 'шоп', 'The shop is open.'),
      w('базар', 'market', 'маркет', 'I go to the market.'),
      w('оорукана', 'hospital', 'хоспитал', 'The hospital is near.'),
      w('китепкана', 'library', 'лайбрари', 'I study in the library.'),
      w('аэропорт', 'airport', 'эапорт', 'The airport is far.'),
      w('парк', 'park', 'парк', 'We walk in the park.'),
      w('ашкана', 'canteen', 'кантин', 'The canteen is full.'),
      w('спорт зал', 'gym', 'жим', 'The gym is new.'),
    ],
  },
  {
    id: 'transport',
    title: 'Транспорт',
    icon: '🚌',
    words: [
      w('унаа', 'car', 'кар', 'The car is fast.'),
      w('автобус', 'bus', 'бас', 'The bus is late.'),
      w('такси', 'taxi', 'такси', 'Call a taxi.'),
      w('поезд', 'train', 'трейн', 'The train is coming.'),
      w('учак', 'plane', 'плейн', 'The plane is flying.'),
      w('велосипед', 'bike', 'байк', 'I ride a bike.'),
      w('аялдама', 'bus stop', 'бас стоп', 'The bus stop is near.'),
      w('билет', 'ticket', 'тикет', 'I bought a ticket.'),
      w('жол', 'road', 'роуд', 'The road is long.'),
      w('түз бар', 'go straight', 'гоу стрейт', 'Go straight, please.'),
      w('оңго бурул', 'turn right', 'терн райт', 'Turn right here.'),
      w('солго бурул', 'turn left', 'терн лефт', 'Turn left there.'),
    ],
  },
  {
    id: 'shopping',
    title: 'Соода',
    icon: '🛒',
    words: [
      w('акча', 'money', 'мани', 'I have money.'),
      w('баа', 'price', 'прайс', 'The price is good.'),
      w('арзан', 'cheap', 'чип', 'This pen is cheap.'),
      w('кымбат', 'expensive', 'икспенсив', 'This phone is expensive.'),
      w('сатып алуу', 'buy', 'бай', 'I want to buy a book.'),
      w('сатуу', 'sell', 'сел', 'They sell bread.'),
      w('карта', 'card', 'кард', 'Can I pay by card?'),
      w('нак акча', 'cash', 'кэш', 'I will pay in cash.'),
      w('чек', 'receipt', 'рисит', 'Can I have a receipt?'),
      w('өлчөм', 'size', 'сайз', 'What size do you need?'),
      w('түс', 'color', 'калер', 'What color do you want?'),
      w('баштык', 'bag', 'бэг', 'I need a bag.'),
    ],
  },
  {
    id: 'health',
    title: 'Ден соолук',
    icon: '🩺',
    words: [
      w('баш', 'head', 'хед', 'My head hurts.'),
      w('көз', 'eye', 'ай', 'My eye is red.'),
      w('кулак', 'ear', 'иер', 'My ear hurts.'),
      w('кол', 'hand', 'хэнд', 'Wash your hands.'),
      w('бут', 'foot', 'фут', 'My foot hurts.'),
      w('оору', 'pain', 'пейн', 'I have pain.'),
      w('дары', 'medicine', 'медисин', 'Take this medicine.'),
      w('дарыгер', 'doctor', 'доктор', 'I need a doctor.'),
      w('температура', 'fever', 'фивер', 'I have a fever.'),
      w('жөтөл', 'cough', 'коф', 'I have a cough.'),
      w('чарчаган', 'tired', 'тайрд', 'I am tired.'),
      w('ден соолук', 'health', 'хелс', 'Health is important.'),
    ],
  },
  {
    id: 'weather',
    title: 'Аба ырайы',
    icon: '🌦️',
    words: [
      w('аба ырайы', 'weather', 'уэзер', 'How is the weather?'),
      w('күн ачык', 'sunny', 'сани', 'It is sunny today.'),
      w('жамгырлуу', 'rainy', 'рейни', 'It is rainy.'),
      w('карлуу', 'snowy', 'сноуи', 'It is snowy.'),
      w('шамалдуу', 'windy', 'уинди', 'It is windy outside.'),
      w('булуттуу', 'cloudy', 'клауди', 'The sky is cloudy.'),
      w('суук', 'cold', 'коулд', 'It is cold today.'),
      w('ысык', 'hot', 'хот', 'Tea is hot.'),
      w('жылуу', 'warm', 'уорм', 'The weather is warm.'),
      w('салкын', 'cool', 'кул', 'The evening is cool.'),
      w('туман', 'fog', 'фог', 'There is fog.'),
      w('асман', 'sky', 'скай', 'The sky is blue.'),
    ],
  },
  {
    id: 'technology',
    title: 'Технология',
    icon: '💻',
    words: [
      w('компьютер', 'computer', 'компьютер', 'I use a computer.'),
      w('телефон', 'phone', 'фоун', 'My phone is new.'),
      w('интернет', 'internet', 'интернет', 'The internet is fast.'),
      w('сайт', 'website', 'вебсайт', 'This website is useful.'),
      w('тиркеме', 'app', 'эп', 'Open the app.'),
      w('сыр сөз', 'password', 'пасворд', 'I forgot my password.'),
      w('файл', 'file', 'файл', 'Open the file.'),
      w('код', 'code', 'коуд', 'I write code.'),
      w('жүктөө', 'download', 'даунлоуд', 'Download the file.'),
      w('жиберүү', 'send', 'сенд', 'Send me a message.'),
      w('сактоо', 'save', 'сейв', 'Save your work.'),
      w('өчүрүү', 'delete', 'дилит', 'Delete this file.'),
    ],
  },
  {
    id: 'emotions',
    title: 'Сезимдер',
    icon: '😊',
    words: [
      w('кубанычтуу', 'happy', 'хэпи', 'I am happy today.'),
      w('кайгылуу', 'sad', 'сэд', 'She is sad.'),
      w('ачуулуу', 'angry', 'энгри', 'Do not be angry.'),
      w('корккон', 'afraid', 'эфрейд', 'I am not afraid.'),
      w('тынч', 'calm', 'кам', 'Stay calm.'),
      w('таң калган', 'surprised', 'сюрпрайзд', 'I am surprised.'),
      w('ачка', 'hungry', 'хангри', 'I am hungry.'),
      w('суусаган', 'thirsty', 'серсти', 'I am thirsty.'),
      w('даяр', 'ready', 'реди', 'I am ready.'),
      w('ишенимдүү', 'sure', 'шур', 'Are you sure?'),
      w('кызыккан', 'interested', 'интерестид', 'I am interested in English.'),
      w('бош эмес', 'busy', 'бизи', 'I am busy now.'),
    ],
  },
  {
    id: 'connectors',
    title: 'Байламталар',
    icon: '🔗',
    words: [
      w('жана', 'and', 'энд', 'You and I.'),
      w('бирок', 'but', 'бат', 'I want to go, but I am busy.'),
      w('анткени', 'because', 'бикоз', 'I study because I want to learn.'),
      w('ошондуктан', 'so', 'соу', 'I am tired, so I will rest.'),
      w('эгер', 'if', 'иф', 'If you want, come with me.'),
      w('же', 'or', 'ор', 'Tea or water?'),
      w('менен', 'with', 'уиз', 'I came with my friend.'),
      w('үчүн', 'for', 'фор', 'This is for you.'),
      w('кийин', 'after', 'афтер', 'After class, I go home.'),
      w('мурун', 'before', 'бифор', 'Read before the lesson.'),
      w('дагы', 'also', 'олсо', 'I also speak Kyrgyz.'),
      w('ошондой эле', 'too', 'ту', 'Me too.'),
    ],
  },
  {
    id: 'ready-sentences',
    title: 'Даяр сүйлөмдөр',
    icon: '✅',
    words: [
      w('Мен бүгүн бош эмесмин', 'I am busy today', 'ай эм бизи тудей', 'I am busy today.'),
      w('Мен азыр келем', 'I am coming now', 'ай эм каминг нау', 'I am coming now.'),
      w('Күтүп туруңуз', 'Please wait', 'плиз уэйт', 'Please wait a minute.'),
      w('Мен сага кийин жазам', 'I will text you later', 'ай вил текст ю лейтер', 'I will text you later.'),
      w('Мен сабак окуп жатам', 'I am studying', 'ай эм стадиинг', 'I am studying now.'),
      w('Кайда барасың?', 'Where are you going?', 'уэа ар ю гоуинг', 'Where are you going?'),
      w('Эмне кылып жатасың?', 'What are you doing?', 'уот ар ю дуинг', 'What are you doing now?'),
      w('Кайдан келдиң?', 'Where did you come from?', 'уэа дид ю кам фром', 'Where did you come from?'),
      w('Баары жакшы болот', 'Everything will be fine', 'эврисинг вил би файн', 'Everything will be fine.'),
      w('Мени менен жүр', 'Come with me', 'кам уиз ми', 'Come with me, please.'),
      w('Мен макулмун', 'I agree', 'ай эгри', 'I agree with you.'),
      w('Мен макул эмесмин', 'I disagree', 'ай дисэгри', 'I disagree with this idea.'),
    ],
  },
];

export const allWords = wordCategories.flatMap((category) =>
  category.words.map((word) => ({ ...word, category: category.title }))
);
